# coding: utf-8

"""
    Mesocycle Planner API - Advanced Periodization

    Complete API for fitness training app with advanced periodization support. Features: 440+ exercises database, Linear/DUP/Block/Polarized periodization models, microcycle management, auto-progression, session logging, and AI-generated training plans.  Supports user authentication, mesocycle planning, workout tracking, and progress analytics. 

    The version of the OpenAPI document: 1.0.0
    Contact: dev@mesocycleplanner.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_server.models.exercise_type import ExerciseType
from openapi_server.models.muscle_group import MuscleGroup
from openapi_server.models.training_level import TrainingLevel
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class Exercise(BaseModel):
    """
    Exercise
    """ # noqa: E501
    id: StrictInt
    name: StrictStr
    number: StrictStr
    muscle_group: MuscleGroup
    type: Optional[ExerciseType] = None
    primary_muscles: List[StrictStr]
    secondary_muscles: Optional[List[StrictStr]] = None
    antagonist_muscles: Optional[List[StrictStr]] = None
    execution: Optional[Annotated[str, Field(strict=True, max_length=2000)]] = None
    comments: Optional[StrictStr] = None
    common_mistakes: Optional[List[StrictStr]] = None
    variants: Optional[List[StrictStr]] = None
    pdf_page: Optional[StrictInt] = None
    difficulty: Optional[TrainingLevel] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["id", "name", "number", "muscle_group", "type", "primary_muscles", "secondary_muscles", "antagonist_muscles", "execution", "comments", "common_mistakes", "variants", "pdf_page", "difficulty", "created_at", "updated_at"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Exercise from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of Exercise from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "number": obj.get("number"),
            "muscle_group": obj.get("muscle_group"),
            "type": obj.get("type"),
            "primary_muscles": obj.get("primary_muscles"),
            "secondary_muscles": obj.get("secondary_muscles"),
            "antagonist_muscles": obj.get("antagonist_muscles"),
            "execution": obj.get("execution"),
            "comments": obj.get("comments"),
            "common_mistakes": obj.get("common_mistakes"),
            "variants": obj.get("variants"),
            "pdf_page": obj.get("pdf_page"),
            "difficulty": obj.get("difficulty"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


