# coding: utf-8

"""
    Mesocycle Planner API - Advanced Periodization

    Complete API for fitness training app with advanced periodization support. Features: 440+ exercises database, Linear/DUP/Block/Polarized periodization models, microcycle management, auto-progression, session logging, and AI-generated training plans.  Supports user authentication, mesocycle planning, workout tracking, and progress analytics. 

    The version of the OpenAPI document: 1.0.0
    Contact: dev@mesocycleplanner.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_server.models.periodization_model import PeriodizationModel
from openapi_server.models.training_goal import TrainingGoal
from openapi_server.models.training_level import TrainingLevel
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class GenerateAIMesocycleRequest(BaseModel):
    """
    GenerateAIMesocycleRequest
    """ # noqa: E501
    goal: TrainingGoal
    duration_weeks: Optional[Annotated[int, Field(le=16, strict=True, ge=4)]] = 12
    periodization_model: Optional[PeriodizationModel] = None
    weekly_frequency: Optional[Annotated[int, Field(le=6, strict=True, ge=3)]] = 5
    training_level: Optional[TrainingLevel] = None
    __properties: ClassVar[List[str]] = ["goal", "duration_weeks", "periodization_model", "weekly_frequency", "training_level"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GenerateAIMesocycleRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of GenerateAIMesocycleRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "goal": obj.get("goal"),
            "duration_weeks": obj.get("duration_weeks") if obj.get("duration_weeks") is not None else 12,
            "periodization_model": obj.get("periodization_model"),
            "weekly_frequency": obj.get("weekly_frequency") if obj.get("weekly_frequency") is not None else 5,
            "training_level": obj.get("training_level")
        })
        return _obj


