# coding: utf-8

"""
    Mesocycle Planner API - Advanced Periodization

    Complete API for fitness training app with advanced periodization support. Features: 440+ exercises database, Linear/DUP/Block/Polarized periodization models, microcycle management, auto-progression, session logging, and AI-generated training plans.  Supports user authentication, mesocycle planning, workout tracking, and progress analytics. 

    The version of the OpenAPI document: 1.0.0
    Contact: dev@mesocycleplanner.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_server.models.get_mesocycle_dashboard200_response_chart_data import GetMesocycleDashboard200ResponseChartData
from openapi_server.models.microcycle import Microcycle
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class GetMesocycleDashboard200Response(BaseModel):
    """
    GetMesocycleDashboard200Response
    """ # noqa: E501
    completion_percentage: Optional[Union[StrictFloat, StrictInt]] = None
    current_phase: Optional[Microcycle] = None
    avg_weekly_volume: Optional[Union[StrictFloat, StrictInt]] = None
    avg_1rm_estimate: Optional[Union[StrictFloat, StrictInt]] = None
    training_adherence: Optional[Union[StrictFloat, StrictInt]] = None
    chart_data: Optional[GetMesocycleDashboard200ResponseChartData] = None
    __properties: ClassVar[List[str]] = ["completion_percentage", "current_phase", "avg_weekly_volume", "avg_1rm_estimate", "training_adherence", "chart_data"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GetMesocycleDashboard200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of current_phase
        if self.current_phase:
            _dict['current_phase'] = self.current_phase.to_dict()
        # override the default output from pydantic by calling `to_dict()` of chart_data
        if self.chart_data:
            _dict['chart_data'] = self.chart_data.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of GetMesocycleDashboard200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "completion_percentage": obj.get("completion_percentage"),
            "current_phase": Microcycle.from_dict(obj.get("current_phase")) if obj.get("current_phase") is not None else None,
            "avg_weekly_volume": obj.get("avg_weekly_volume"),
            "avg_1rm_estimate": obj.get("avg_1rm_estimate"),
            "training_adherence": obj.get("training_adherence"),
            "chart_data": GetMesocycleDashboard200ResponseChartData.from_dict(obj.get("chart_data")) if obj.get("chart_data") is not None else None
        })
        return _obj


