# coding: utf-8

"""
    Mesocycle Planner API - Advanced Periodization

    Complete API for fitness training app with advanced periodization support. Features: 440+ exercises database, Linear/DUP/Block/Polarized periodization models, microcycle management, auto-progression, session logging, and AI-generated training plans.  Supports user authentication, mesocycle planning, workout tracking, and progress analytics. 

    The version of the OpenAPI document: 1.0.0
    Contact: dev@mesocycleplanner.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.microcycle import Microcycle
from openapi_server.models.training_day import TrainingDay
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class GetMicrocycle200Response(BaseModel):
    """
    GetMicrocycle200Response
    """ # noqa: E501
    microcycle: Optional[Microcycle] = None
    training_days: Optional[List[TrainingDay]] = None
    intensity_guidelines: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["microcycle", "training_days", "intensity_guidelines"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GetMicrocycle200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of microcycle
        if self.microcycle:
            _dict['microcycle'] = self.microcycle.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in training_days (list)
        _items = []
        if self.training_days:
            for _item in self.training_days:
                if _item:
                    _items.append(_item.to_dict())
            _dict['training_days'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of GetMicrocycle200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "microcycle": Microcycle.from_dict(obj.get("microcycle")) if obj.get("microcycle") is not None else None,
            "training_days": [TrainingDay.from_dict(_item) for _item in obj.get("training_days")] if obj.get("training_days") is not None else None,
            "intensity_guidelines": obj.get("intensity_guidelines")
        })
        return _obj


