# coding: utf-8

"""
    Mesocycle Planner API - Advanced Periodization

    Complete API for fitness training app with advanced periodization support. Features: 440+ exercises database, Linear/DUP/Block/Polarized periodization models, microcycle management, auto-progression, session logging, and AI-generated training plans.  Supports user authentication, mesocycle planning, workout tracking, and progress analytics. 

    The version of the OpenAPI document: 1.0.0
    Contact: dev@mesocycleplanner.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_server.models.get_progress_analytics200_response_data_points_inner import GetProgressAnalytics200ResponseDataPointsInner
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class GetProgressAnalytics200Response(BaseModel):
    """
    GetProgressAnalytics200Response
    """ # noqa: E501
    metric_type: Optional[StrictStr] = None
    average: Optional[Union[StrictFloat, StrictInt]] = None
    min: Optional[Union[StrictFloat, StrictInt]] = None
    max: Optional[Union[StrictFloat, StrictInt]] = None
    trend: Optional[StrictStr] = None
    data_points: Optional[List[GetProgressAnalytics200ResponseDataPointsInner]] = None
    __properties: ClassVar[List[str]] = ["metric_type", "average", "min", "max", "trend", "data_points"]

    @field_validator('trend')
    def trend_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('increasing', 'decreasing', 'stable',):
            raise ValueError("must be one of enum values ('increasing', 'decreasing', 'stable')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GetProgressAnalytics200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in data_points (list)
        _items = []
        if self.data_points:
            for _item in self.data_points:
                if _item:
                    _items.append(_item.to_dict())
            _dict['data_points'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of GetProgressAnalytics200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "metric_type": obj.get("metric_type"),
            "average": obj.get("average"),
            "min": obj.get("min"),
            "max": obj.get("max"),
            "trend": obj.get("trend"),
            "data_points": [GetProgressAnalytics200ResponseDataPointsInner.from_dict(_item) for _item in obj.get("data_points")] if obj.get("data_points") is not None else None
        })
        return _obj


