# coding: utf-8

"""
    Mesocycle Planner API - Advanced Periodization

    Complete API for fitness training app with advanced periodization support. Features: 440+ exercises database, Linear/DUP/Block/Polarized periodization models, microcycle management, auto-progression, session logging, and AI-generated training plans.  Supports user authentication, mesocycle planning, workout tracking, and progress analytics. 

    The version of the OpenAPI document: 1.0.0
    Contact: dev@mesocycleplanner.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_server.models.progression_recommendation import ProgressionRecommendation
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class GetMesocycleProgression200Response(BaseModel):
    """
    GetMesocycleProgression200Response
    """ # noqa: E501
    next_week_weights: Optional[List[ProgressionRecommendation]] = None
    projected_volume: Optional[Union[StrictFloat, StrictInt]] = None
    expected_rpe: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["next_week_weights", "projected_volume", "expected_rpe"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GetMesocycleProgression200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in next_week_weights (list)
        _items = []
        if self.next_week_weights:
            for _item in self.next_week_weights:
                if _item:
                    _items.append(_item.to_dict())
            _dict['next_week_weights'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of GetMesocycleProgression200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "next_week_weights": [ProgressionRecommendation.from_dict(_item) for _item in obj.get("next_week_weights")] if obj.get("next_week_weights") is not None else None,
            "projected_volume": obj.get("projected_volume"),
            "expected_rpe": obj.get("expected_rpe")
        })
        return _obj


