# coding: utf-8

"""
    Mesocycle Planner API - Advanced Periodization

    Complete API for fitness training app with advanced periodization support. Features: 440+ exercises database, Linear/DUP/Block/Polarized periodization models, microcycle management, auto-progression, session logging, and AI-generated training plans.  Supports user authentication, mesocycle planning, workout tracking, and progress analytics. 

    The version of the OpenAPI document: 1.0.0
    Contact: dev@mesocycleplanner.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class MesocycleStatus(str, Enum):
    """
    MesocycleStatus
    """

    """
    allowed enum values
    """
    PLANNED = 'planned'
    ACTIVE = 'active'
    COMPLETED = 'completed'
    PAUSED = 'paused'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MesocycleStatus from a JSON string"""
        return cls(json.loads(json_str))


