# coding: utf-8

"""
    Mesocycle Planner API - Advanced Periodization

    Complete API for fitness training app with advanced periodization support. Features: 440+ exercises database, Linear/DUP/Block/Polarized periodization models, microcycle management, auto-progression, session logging, and AI-generated training plans.  Supports user authentication, mesocycle planning, workout tracking, and progress analytics. 

    The version of the OpenAPI document: 1.0.0
    Contact: dev@mesocycleplanner.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_server.models.microcycle import Microcycle
from openapi_server.models.periodization_model import PeriodizationModel
from openapi_server.models.training_goal import TrainingGoal
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class MesocycleCreate(BaseModel):
    """
    MesocycleCreate
    """ # noqa: E501
    name: StrictStr
    description: Optional[StrictStr] = None
    periodization_model: Optional[PeriodizationModel] = None
    goal: TrainingGoal
    start_date: date
    end_date: date
    weekly_frequency: Annotated[int, Field(le=6, strict=True, ge=3)]
    duration_weeks: Optional[Annotated[int, Field(le=16, strict=True, ge=4)]] = None
    microcycles: Optional[List[Microcycle]] = None
    __properties: ClassVar[List[str]] = ["name", "description", "periodization_model", "goal", "start_date", "end_date", "weekly_frequency", "duration_weeks", "microcycles"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MesocycleCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in microcycles (list)
        _items = []
        if self.microcycles:
            for _item in self.microcycles:
                if _item:
                    _items.append(_item.to_dict())
            _dict['microcycles'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of MesocycleCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "description": obj.get("description"),
            "periodization_model": obj.get("periodization_model"),
            "goal": obj.get("goal"),
            "start_date": obj.get("start_date"),
            "end_date": obj.get("end_date"),
            "weekly_frequency": obj.get("weekly_frequency"),
            "duration_weeks": obj.get("duration_weeks"),
            "microcycles": [Microcycle.from_dict(_item) for _item in obj.get("microcycles")] if obj.get("microcycles") is not None else None
        })
        return _obj


