# coding: utf-8

"""
    Mesocycle Planner API - Advanced Periodization

    Complete API for fitness training app with advanced periodization support. Features: 440+ exercises database, Linear/DUP/Block/Polarized periodization models, microcycle management, auto-progression, session logging, and AI-generated training plans.  Supports user authentication, mesocycle planning, workout tracking, and progress analytics. 

    The version of the OpenAPI document: 1.0.0
    Contact: dev@mesocycleplanner.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import date, datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_server.models.mesocycle_status import MesocycleStatus
from openapi_server.models.microcycle import Microcycle
from openapi_server.models.periodization_model import PeriodizationModel
from openapi_server.models.training_day import TrainingDay
from openapi_server.models.training_goal import TrainingGoal
from openapi_server.models.training_level import TrainingLevel
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class Mesocycle(BaseModel):
    """
    Mesocycle
    """ # noqa: E501
    id: StrictStr
    user_id: StrictStr
    name: StrictStr
    description: Optional[StrictStr] = None
    periodization_model: PeriodizationModel
    goal: TrainingGoal
    duration_weeks: Annotated[int, Field(le=16, strict=True, ge=4)]
    start_date: date
    end_date: date
    status: MesocycleStatus
    training_level: Optional[TrainingLevel] = None
    weekly_frequency: Optional[Annotated[int, Field(le=6, strict=True, ge=3)]] = None
    microcycles: Optional[Annotated[List[Microcycle], Field(min_length=3)]] = None
    weekly_structure: Optional[List[TrainingDay]] = None
    deload_weeks: Optional[List[StrictInt]] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["id", "user_id", "name", "description", "periodization_model", "goal", "duration_weeks", "start_date", "end_date", "status", "training_level", "weekly_frequency", "microcycles", "weekly_structure", "deload_weeks", "created_at", "updated_at"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Mesocycle from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in microcycles (list)
        _items = []
        if self.microcycles:
            for _item in self.microcycles:
                if _item:
                    _items.append(_item.to_dict())
            _dict['microcycles'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in weekly_structure (list)
        _items = []
        if self.weekly_structure:
            for _item in self.weekly_structure:
                if _item:
                    _items.append(_item.to_dict())
            _dict['weekly_structure'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of Mesocycle from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "user_id": obj.get("user_id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "periodization_model": obj.get("periodization_model"),
            "goal": obj.get("goal"),
            "duration_weeks": obj.get("duration_weeks"),
            "start_date": obj.get("start_date"),
            "end_date": obj.get("end_date"),
            "status": obj.get("status"),
            "training_level": obj.get("training_level"),
            "weekly_frequency": obj.get("weekly_frequency"),
            "microcycles": [Microcycle.from_dict(_item) for _item in obj.get("microcycles")] if obj.get("microcycles") is not None else None,
            "weekly_structure": [TrainingDay.from_dict(_item) for _item in obj.get("weekly_structure")] if obj.get("weekly_structure") is not None else None,
            "deload_weeks": obj.get("deload_weeks"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


