# coding: utf-8

"""
    Mesocycle Planner API - Advanced Periodization

    Complete API for fitness training app with advanced periodization support. Features: 440+ exercises database, Linear/DUP/Block/Polarized periodization models, microcycle management, auto-progression, session logging, and AI-generated training plans.  Supports user authentication, mesocycle planning, workout tracking, and progress analytics. 

    The version of the OpenAPI document: 1.0.0
    Contact: dev@mesocycleplanner.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_server.models.microcycle_intensity_range import MicrocycleIntensityRange
from openapi_server.models.training_phase import TrainingPhase
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class Microcycle(BaseModel):
    """
    Microcycle
    """ # noqa: E501
    id: StrictInt
    mesocycle_id: StrictInt
    microcycle_number: StrictInt
    week_start: Optional[StrictInt] = None
    week_end: Optional[StrictInt] = None
    phase: TrainingPhase
    intensity_range: Optional[MicrocycleIntensityRange] = None
    reps_range: Optional[StrictStr] = None
    sets_range: Optional[StrictStr] = None
    rir: Optional[StrictInt] = Field(default=None, description="Reps In Reserve")
    weekly_volume_multiplier: Optional[Union[StrictFloat, StrictInt]] = None
    frequency_per_week: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["id", "mesocycle_id", "microcycle_number", "week_start", "week_end", "phase", "intensity_range", "reps_range", "sets_range", "rir", "weekly_volume_multiplier", "frequency_per_week"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Microcycle from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of intensity_range
        if self.intensity_range:
            _dict['intensity_range'] = self.intensity_range.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of Microcycle from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "mesocycle_id": obj.get("mesocycle_id"),
            "microcycle_number": obj.get("microcycle_number"),
            "week_start": obj.get("week_start"),
            "week_end": obj.get("week_end"),
            "phase": obj.get("phase"),
            "intensity_range": MicrocycleIntensityRange.from_dict(obj.get("intensity_range")) if obj.get("intensity_range") is not None else None,
            "reps_range": obj.get("reps_range"),
            "sets_range": obj.get("sets_range"),
            "rir": obj.get("rir"),
            "weekly_volume_multiplier": obj.get("weekly_volume_multiplier"),
            "frequency_per_week": obj.get("frequency_per_week")
        })
        return _obj


