# coding: utf-8

"""
    Mesocycle Planner API - Advanced Periodization

    Complete API for fitness training app with advanced periodization support. Features: 440+ exercises database, Linear/DUP/Block/Polarized periodization models, microcycle management, auto-progression, session logging, and AI-generated training plans.  Supports user authentication, mesocycle planning, workout tracking, and progress analytics. 

    The version of the OpenAPI document: 1.0.0
    Contact: dev@mesocycleplanner.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class PeriodizationModel(str, Enum):
    """
    linear: Volume↑→Intensity↑ | daily_undulating: Daily rep changes |  block: Sequential focus phases | polarized: 80/20 intensity distribution 
    """

    """
    allowed enum values
    """
    LINEAR = 'linear'
    DAILY_UNDULATING = 'daily_undulating'
    BLOCK = 'block'
    POLARIZED = 'polarized'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PeriodizationModel from a JSON string"""
        return cls(json.loads(json_str))


