# coding: utf-8

"""
    Mesocycle Planner API - Advanced Periodization

    Complete API for fitness training app with advanced periodization support. Features: 440+ exercises database, Linear/DUP/Block/Polarized periodization models, microcycle management, auto-progression, session logging, and AI-generated training plans.  Supports user authentication, mesocycle planning, workout tracking, and progress analytics. 

    The version of the OpenAPI document: 1.0.0
    Contact: dev@mesocycleplanner.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.training_session_exercises_performed_inner_sets_performed_inner import TrainingSessionExercisesPerformedInnerSetsPerformedInner
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class TrainingSessionExercisesPerformedInner(BaseModel):
    """
    TrainingSessionExercisesPerformedInner
    """ # noqa: E501
    exercise_id: Optional[StrictInt] = None
    planned_sets: Optional[StrictInt] = None
    sets_performed: Optional[List[TrainingSessionExercisesPerformedInnerSetsPerformedInner]] = None
    __properties: ClassVar[List[str]] = ["exercise_id", "planned_sets", "sets_performed"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TrainingSessionExercisesPerformedInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in sets_performed (list)
        _items = []
        if self.sets_performed:
            for _item in self.sets_performed:
                if _item:
                    _items.append(_item.to_dict())
            _dict['sets_performed'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of TrainingSessionExercisesPerformedInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "exercise_id": obj.get("exercise_id"),
            "planned_sets": obj.get("planned_sets"),
            "sets_performed": [TrainingSessionExercisesPerformedInnerSetsPerformedInner.from_dict(_item) for _item in obj.get("sets_performed")] if obj.get("sets_performed") is not None else None
        })
        return _obj


