# coding: utf-8

"""
    Mesocycle Planner API - Advanced Periodization

    Complete API for fitness training app with advanced periodization support. Features: 440+ exercises database, Linear/DUP/Block/Polarized periodization models, microcycle management, auto-progression, session logging, and AI-generated training plans.  Supports user authentication, mesocycle planning, workout tracking, and progress analytics. 

    The version of the OpenAPI document: 1.0.0
    Contact: dev@mesocycleplanner.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.training_split import TrainingSplit
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class Workout(BaseModel):
    """
    Workout
    """ # noqa: E501
    id: StrictStr
    mesocycle_id: StrictStr
    microcycle_id: Optional[StrictInt] = None
    name: StrictStr
    description: Optional[StrictStr] = None
    scheduled_date: datetime
    completed: Optional[StrictBool] = False
    completed_at: Optional[datetime] = None
    duration_minutes: Optional[StrictInt] = None
    notes: Optional[StrictStr] = None
    split: Optional[TrainingSplit] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["id", "mesocycle_id", "microcycle_id", "name", "description", "scheduled_date", "completed", "completed_at", "duration_minutes", "notes", "split", "created_at", "updated_at"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Workout from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of Workout from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "mesocycle_id": obj.get("mesocycle_id"),
            "microcycle_id": obj.get("microcycle_id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "scheduled_date": obj.get("scheduled_date"),
            "completed": obj.get("completed") if obj.get("completed") is not None else False,
            "completed_at": obj.get("completed_at"),
            "duration_minutes": obj.get("duration_minutes"),
            "notes": obj.get("notes"),
            "split": obj.get("split"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


