# coding: utf-8

"""
    Mesocycle Planner API - Advanced Periodization

    Complete API for fitness training app with advanced periodization support. Features: 440+ exercises database, Linear/DUP/Block/Polarized periodization models, microcycle management, auto-progression, session logging, and AI-generated training plans.  Supports user authentication, mesocycle planning, workout tracking, and progress analytics. 

    The version of the OpenAPI document: 1.0.0
    Contact: dev@mesocycleplanner.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.authentication_api import router as AuthenticationApiRouter
from openapi_server.apis.exercises_api import router as ExercisesApiRouter
from openapi_server.apis.mesocycles_api import router as MesocyclesApiRouter
from openapi_server.apis.progress_api import router as ProgressApiRouter
from openapi_server.apis.progression_api import router as ProgressionApiRouter
from openapi_server.apis.tracking_api import router as TrackingApiRouter
from openapi_server.apis.users_api import router as UsersApiRouter
from openapi_server.apis.workouts_api import router as WorkoutsApiRouter

app = FastAPI(
    title="Mesocycle Planner API - Advanced Periodization",
    description="Complete API for fitness training app with advanced periodization support. Features: 440+ exercises database, Linear/DUP/Block/Polarized periodization models, microcycle management, auto-progression, session logging, and AI-generated training plans.  Supports user authentication, mesocycle planning, workout tracking, and progress analytics. ",
    version="1.0.0",
)

app.include_router(AuthenticationApiRouter)
app.include_router(ExercisesApiRouter)
app.include_router(MesocyclesApiRouter)
app.include_router(ProgressApiRouter)
app.include_router(ProgressionApiRouter)
app.include_router(TrackingApiRouter)
app.include_router(UsersApiRouter)
app.include_router(WorkoutsApiRouter)
