"""Implementation package for OpenAPI server.

Import concrete API implementations so the autogenerated routers can
discover subclasses of the Base*Api classes.
"""

from . import exercises_impl
from . import users_impl
from . import authentication_impl
from . import progression_impl

# New implementations (safe to add here)
from . import mesocycles_impl
from . import workouts_impl
from . import progress_impl
from . import tracking_impl
